project:
  type: book

book:
  title: "FLIM Playground"
  author: "Wenxuan Zhao"
  date: "7/30/2025"
  repo-url: https://github.com/skalalab/flim_playground_doc
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Data Extraction"
      chapters:
        - data_extraction.qmd
        - data_extraction_config.qmd
        - fov_metadata.qmd
        - numerical_feature_extraction.qmd
        - lifetime_fit.qmd
        - lifetime_fit_free.qmd
        - intensity_morphology.qmd
        - intensity_texture.qmd
        - categorical_feature_extraction.qmd
    - part: "Data Analysis"
      chapters:
        - data_analysis.qmd
        - data_analysis_config.qmd
    - part: "Univariate Analysis"
      chapters:
        - feature_comparison.qmd
        - feature_histogram.qmd
        - fov_comparison.qmd
    - part: "Bivariate Analysis"
      chapters:
        - feature_distribution.qmd
        - phasor_analysis.qmd
    - part: "Multivariate Analysis"
      chapters:
        - dimension_reduction.qmd
        - classification.qmd
    - common_qa.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/nature

format:
  html:
    theme:
      light: [flatly, brand]
      dark: [darkly, brand]
    number-sections: true
    number-depth: 3
    citations-hover: true
    footnotes-hover: true
    include-after-body: giscus.html
    reference-location: document
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex
    top-level-division: chapter
    shift-headings: -1
    title: "FLIM Playground Supplemental Manual"
    author: []
    date: ""
    include-in-header: pdf-title.tex
